import type { Member } from '@/types/member';

// TODO: Replace this mock data with the members list API response when the backend endpoint is ready.
export const members: Member[] = [
  {
    id: 'jo-yein',
    name: '조예인',
    role: 'Organizer',
    tags: ['AI/ML', 'DevRel'],
  },
  {
    id: 'lee-yeonjae',
    name: '이연재',
    role: 'Team Member',
    tags: ['App/Web', 'Frontend'],
    imageKey: '이연재',
  },
  {
    id: 'kim-hyena',
    name: '김혜나',
    role: 'Team Member',
    tags: ['AI/ML', 'Cloud'],
    imageKey: '김혜나',
  },
  {
    id: 'choi-seoyoung',
    name: '최서영',
    role: 'Team Member',
    tags: ['AI/ML', 'Cloud'],
  },
  {
    id: 'choi-yoonseo',
    name: '최윤서',
    role: 'Team Member',
    tags: ['AI/ML', 'Cloud'],
  },
  {
    id: 'je-yujin',
    name: '제유진',
    role: 'Team Member',
    tags: ['AI/ML', 'Cloud'],
  },
  {
    id: 'lee-haneul',
    name: '이하늘',
    role: 'Team Member',
    tags: ['Cloud', 'Backend'],
  },
  {
    id: 'lee-gyeongeun',
    name: '이경은',
    role: 'Team Member',
    tags: ['Spring', 'Backend'],
    imageKey: '이경은',
  },
  {
    id: 'choi-woojin',
    name: '최우진',
    role: 'Team Member',
    tags: ['AI/ML', 'Cloud'],
  },
  {
    id: 'kim-minyoung',
    name: '김민영',
    role: 'Team Member',
    tags: ['AI/ML', 'Cloud'],
    imageKey: '김민영',
  },
  {
    id: 'kwak-haerim',
    name: '곽해림',
    role: 'Team Member',
    tags: ['AI/ML', 'Frontend'],
    imageKey: '곽해림',
  },
  {
    id: 'oh-hyunseo',
    name: '오현서',
    role: 'Team Member',
    tags: ['App/Web', 'Frontend'],
    imageKey: '오현서',
  },
  {
    id: 'yoo-gayeon',
    name: '유가연',
    role: 'Member',
    tags: ['AI/ML', 'DevRel'],
  },
  {
    id: 'hwang-jiwon',
    name: '황지원',
    role: 'Member',
    tags: ['AI/ML', 'Frontend'],
  },
  {
    id: 'song-yumin',
    name: '송유민',
    role: 'Member',
    tags: ['AI/ML', 'DevRel'],
    imageKey: '송유민',
  },
  {
    id: 'choi-doyeon',
    name: '최도연',
    role: 'Member',
    tags: ['App/Web', 'Frontend'],
  },
  {
    id: 'song-sihyun',
    name: '송시현',
    role: 'Member',
    tags: ['AI/ML', 'DevRel'],
  },
  {
    id: 'ryu-hyeseong',
    name: '류혜성',
    role: 'Member',
    tags: ['AI/ML', 'Cloud'],
  },
  {
    id: 'jang-yeeun',
    name: '장예은',
    role: 'Member',
    tags: ['AI/ML', 'DevRel'],
  },
  {
    id: 'oh-yowon',
    name: '오요원',
    role: 'Member',
    tags: ['AI/ML', 'DevRel'],
  },
  {
    id: 'lee-chaeyoung',
    name: '이채영',
    role: 'Member',
    tags: ['AI/ML', 'DevRel'],
    imageKey: '이채영',
  },
  {
    id: 'hyun-soyoon',
    name: '현소윤',
    role: 'Member',
    tags: ['AI/ML', 'DevRel'],
    imageKey: '현소윤',
  },
  {
    id: 'kim-chanran',
    name: '김찬란',
    role: 'Member',
    tags: ['AI/ML', 'DevRel'],
    imageKey: '김찬란',
  },
  {
    id: 'lee-chaeyeon',
    name: '이채연',
    role: 'Member',
    tags: ['AI/ML', 'DevRel'],
    imageKey: '이채연',
  },
  {
    id: 'jeong-eunseo',
    name: '정은서',
    role: 'Member',
    tags: ['Spring', 'Backend'],
  },
  {
    id: 'song-haeun',
    name: '송하은',
    role: 'Member',
    tags: ['Spring', 'Backend'],
  },
  {
    id: 'ahn-chaewon',
    name: '안채원',
    role: 'Member',
    tags: ['Spring', 'Backend'],
  },
  {
    id: 'lee-juwon',
    name: '이주원',
    role: 'Member',
    tags: ['Spring', 'Backend'],
  },
  {
    id: 'kwon-jaehee',
    name: '권재희',
    role: 'Member',
    tags: ['Spring', 'Backend'],
  },
  {
    id: 'lee-eunyoung',
    name: '이은영',
    role: 'Member',
    tags: ['Spring', 'Backend'],
  },
  {
    id: 'lee-giju',
    name: '이기주',
    role: 'Member',
    tags: ['Backend', 'Cloud'],
    imageKey: '이기주',
  },
];
