import type { Activity, ActivityQuarter } from '@/types/activity';

export const activityQuarters: {
  id: ActivityQuarter;
  label: string;
}[] = [
  { id: 'Q1', label: '1분기' },
  { id: 'Q2', label: '2분기' },
  { id: 'Q3', label: '3분기' },
];

// TODO: Replace these static activities with the activities list API response when the backend endpoint is ready.
export const activities: Activity[] = [
  {
    id: 'q1-study',
    quarter: 'Q1',
    period: '9월 ~ 12월',
    title: '1분기 스터디',
    description: ['Spring, Flutter, React, AI/DL', '총 4개 스터디 운영'],
    imageFileName: '[1] 1분기 스터디.png',
  },
  {
    id: 'q1-team-member-speaker-session',
    quarter: 'Q1',
    period: '9월 ~ 12월',
    title: '팀멤버 스피커세션',
    description: ['운영진이', '지식과 경험을 공유하는 발표 세션'],
    imageFileName: '[2] 팀멤버 스피커 세션.png',
  },
  {
    id: 'q1-git-github-hands-on',
    quarter: 'Q1',
    period: '9월',
    title: 'Git & GitHub Hands-on',
    description: ['Git 및 GitHub 활용 방법 학습', '협업 역량 강화를 위한 실습 워크숍'],
    imageFileName: '[3] Git & GitHub Hands-on.PNG',
  },
  {
    id: 'q1-company-speaker-session',
    quarter: 'Q1',
    period: '9월',
    title: '기업 연사자 초청 세션',
    description: ['현업 개발자의', '경험과 인사이트를 듣는 특강'],
    imageFileName: '[4] 기업 연사자 초청 세션.jpg',
  },
  {
    id: 'q1-hoodie-group-buy',
    quarter: 'Q1',
    period: '10월',
    title: '후드집업 공동구매',
    description: ['커뮤니티 소속감을 높이기 위한', '굿즈 공동 제작 및 구매 이벤트'],
    imageFileName: '[5] 후드집업 공동 구매.jpg',
  },
  {
    id: 'q1-study-together',
    quarter: 'Q1',
    period: '10월',
    title: '시험기간 모각공 이벤트',
    description: ['스노우버스에서 시험기간 동안', '함께 모여 공부하는 모각공 이벤트'],
    imageFileName: '[6] 시험기간 모각공 이벤트.png',
  },
  {
    id: 'q1-devfest',
    quarter: 'Q1',
    period: '10월',
    title: 'DevFest',
    description: ['GDGoC 선배 개발자의 경험과', '진로 이야기를 듣는 커리어 특강'],
    imageFileName: '[7] DevFest.png',
  },
  {
    id: 'q1-graduate-speaker-session',
    quarter: 'Q1',
    period: '11월',
    title: '졸업생 초청 강연',
    description: ['GDGoC 선배 개발자의 경험과', '진로 이야기를 듣는 커리어 특강'],
    imageFileName: '[8] 졸업생초청강연.jpeg',
  },
  {
    id: 'q1-retrospective',
    quarter: 'Q1',
    period: '12월',
    title: '1분기 회고',
    description: ['1분기 활동을 돌아보고', '개선 방향을 도출하는 정리 세션'],
    imageFileName: '[9] 1분기 회고.jpg',
  },
  {
    id: 'q2-project-orientation',
    quarter: 'Q2',
    period: '1월',
    title: '연합프로젝트 오리엔테이션',
    description: ['GDGoC 서강대학교, 성균관대학교,', '서울과학기술대학교 연합 프로젝트'],
    imageFileName: '[1] 연합프로젝트 오리엔테이션.jpg',
  },
  {
    id: 'q2-union-session',
    quarter: 'Q2',
    period: '1월',
    title: '숙명 x 건국 x 동국 연합 세션',
    description: ['타 대학 GDGoC 멤버들과 함께하는', '기술 교류 및 네트워킹 세션'],
    imageFileName: '[2] 숙명건국동국 연합세션.JPG',
  },
  {
    id: 'q2-one-wave',
    quarter: 'Q2',
    period: '2월',
    title: 'GDG Hackathon : One Wave',
    description: ['아이디어를 실제 서비스로 구현하는', '1박 2일 해커톤'],
    imageFileName: '[3] GDG 해커톤 One Wave.jpg',
  },
  {
    id: 'q2-design-sprint',
    quarter: 'Q2',
    period: '2월',
    title: '연합프로젝트 Design Sprint',
    description: ['문제를 정의하고 솔루션을 구체화하는', '아이디어 교류 세션'],
    imageFileName: '[4] 연합프로젝트 Design Sprint Feedback.jpg',
  },
  {
    id: 'q2-mid-demo',
    quarter: 'Q2',
    period: '2월',
    title: '연합프로젝트 Mid-Demo Day',
    description: ['프로젝트 진행 현황을 공유하고', '피드백을 받는 중간 발표 세션'],
    imageFileName: '[5] 연합프로젝트 Mid-Demo.jpg',
  },
  {
    id: 'q3-snowball-seminar',
    quarter: 'Q3',
    period: '3월 ~ 5월',
    title: '스노우볼 세미나',
    description: ['멤버들이', '지식과 경험을 공유하는 발표 세션'],
    imageFileName: '[1] 스노우볼세미나.JPG',
  },
  {
    id: 'q3-innovate-her',
    quarter: 'Q3',
    period: '3월',
    title: 'Innovate Her',
    description: ['기술 분야 여성 인재들의 성장을 위한', '커뮤니티 네트워킹 행사'],
    imageFileName: '[2] innovate_her.jpg',
  },
  {
    id: 'q3-picnic',
    quarter: 'Q3',
    period: '3월',
    title: 'GDG 숙명 피크닉',
    description: ['멤버 간 친목과 교류를 위한', '피크닉 이벤트'],
    imageFileName: '[3] GDG 숙명 피크닉.jpeg',
  },
  {
    id: 'q3-april-fools-networking',
    quarter: 'Q3',
    period: '4월',
    title: '만우절 기념 네트워킹 세션',
    description: ['라이어게임을 통한', '커뮤니티 교류 증진 네트워킹 세션'],
    imageFileName: '[4] 만우절 기념 네트워킹 세션.jpg',
  },
  {
    id: 'q3-build-with-ai',
    quarter: 'Q3',
    period: '5월',
    title: 'Build with AI',
    description: ['최신 AI 기술을 직접 실습하는', 'Google AI Hands-on 세션'],
    imageFileName: '[5] build_with_ai.jpeg',
  },
  {
    id: 'q3-cloud-union-session',
    quarter: 'Q3',
    period: '5월',
    title: '클라우드 연합 세션',
    description: ['클라우드 기술 학습을 위한', '성균관대학교 연합 기술 세션'],
    imageFileName: '[6] 클라우드연합세션.jpg',
  },
  {
    id: 'q3-graduation',
    quarter: 'Q3',
    period: '5월',
    title: '졸업식',
    description: ['한 기수의 활동을 마무리하는', '수료 및 네트워킹 행사'],
    imageFileName: '[7] 졸업식.jpeg',
  },
  {
    id: 'q3-final-demo',
    quarter: 'Q3',
    period: '6월',
    title: '연합프로젝트 Final Demo',
    description: ['프로젝트 최종 결과물을 발표하는', '성과 공유 행사'],
    imageFileName: '[8] final-demo.jpg',
  },
];
